language: c
compiler: gcc
sudo: false
cache:
    directories:
        - perl_modules
before_install:
    - export PERL_MM_USE_DEFAULT=1
    - export PERL5LIB=/home/travis/perl5/lib/perl5
    - cpanm local::lib
    - eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"
install: cpan -f -i Template
script: make && make test
