language: c
compiler: gcc
sudo: false
cache:
    directories:
        - perl_modules
before_install:
    - export PERL_MM_USE_DEFAULT=1
    - cpanm --local-lib=~/perl_modules local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib=~/perl_modules)
install: cpan -f -i Template
script: make && make test
